print("We'll make some calculations, enter numbers A and B")
a = float(input("Enter A "))
b = float(input("Enter B "))
print("A + B = ", a + b)
print("A - B = ", a - b)
print("A * B = ", a * b)
print("A / B = ", a / b)
print("A**B = ", a ** b)
print("A // B = ", a // b)
print("A % B = ", a % b)